origin_resource = "subscription"
provider = { "json!" = "provider.json", jmespath = '["Amazon Web Services"]' }

[[create_resource]]
create_from = { property = "environment", as = "account" }
relation_type = "SATISFIES"
name = "AWS-{{- origin_resource.name | upper -}}-{{- property.value | upper -}}"
[create_resource.properties]
function = "salesforce"
provider = "{{- provider -}}"
environment = "{{- property.value | lower -}}"
home_region = "{{- origin_resource.home | lower -}}"
template = "Core"
resolver = ["private"] # Determines the scope, valid entries are "private" and "public"
key = "kpt-sf-prod"
login = ["account-administrator"]
description = "The {{ origin_resource.name | lower }} account is a secure digital identity that grants authorized access to AWS's cloud resources and enables a centralized management hub to automate cloud service deployments and configurations."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

origin_resource = "identity"

[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "dev-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "DEV" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]

[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "int-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "INT" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]


[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "prod-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "PROD" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]

[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "sre-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "SRE" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]
