origin_resource = "provider"

[[create_resource]]
create_from = { property = "account" }
relation_type = "SATISFIES"
name = "{{- origin_resource.name | upper -}}-{{- origin_resource.subscription[0].name | upper -}}-{{- property.value | upper -}}"
[create_resource.properties]
function = "salesforce"
provider = "{{- origin_resource.name | lower -}}"
environment = "{{- property.value | lower -}}"
template = "Core"
key = "kpt-sf-prod"
login = ["account-administrator"]
description = "The {{ origin_resource.name  }} account is a secure digital identity that grants authorized access to {{ origin_resource.name | capitalize }}'s cloud resources and enables a centralized management hub to automate cloud service deployments and configurations."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

[[create_resource]]
resource_type = "account"
relation_type = "SATISFIES"
name = "{{- origin_resource.name | upper -}}-{{- origin_resource.subscription[0].name | upper -}}-SRE"
[create_resource.properties]
function = "development"
provider = "{{- origin_resource.name | lower -}}"
environment = "sre"
template = "Core"
key = "kpt-sre"
login = ["account-administrator"]
description = "The {{ origin_resource.name  }} account is a secure digital identity that grants authorized access to {{ origin_resource.name | capitalize }}'s cloud resources and enables a centralized management hub to automate cloud service deployments and configurations."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

origin_resource = "subscription"

[[link_resources]]
with = "account"
join = { local = "provider", remote = "provider" }
create_relation = { type = "DEFINED_BY" }
copy_properties = [
  { from = "home", as = "home_region" }
]

origin_resource = "identity"

[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "dev-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "DEV" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]

[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "int-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "INT" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]


[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "prod-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "PROD" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]

[[link_resources]]
with = "account"
match_on = [{ property = "name", value = "sre-administrator" }]
create_relation = { type = "RESPONSIBLE_FOR" }
match_with = [{ property = "environment", value = "SRE" }]
copy_properties = [
  { from = "name", as = "technical_contact" },
  { from = "email", as = "email" }
]
