origin_resource = "account"
provider = { "json!" = "provider.json", jmespath = '["Amazon Web Services"]' }

[[create_resource]]
create_from = { property = "resolver" }
relation_type = "DEFINED_BY"
name = "{{- origin_resource.name | lower -}}-{{- property.value | lower -}}-dns"
[create_resource.properties]
function = "{{- property.value | lower -}}-dns"
provider = "{{- provider -}}"
description = "The {{ property.value | lower }} DNS service is a managed, authoritative name server cluster that operates exclusively within the control plane of a Virtual Private Cloud (VPC) or Virtual Network (VNET)."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

origin_resource = "dns"

[[link_resources]]
with = "resolver"
join = { local = "name", remote = "function" }
copy_properties = [
  { from = "zones", as = "zone" }
]
create_relation = { type = "DEFINED_BY" }
